; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8C4CCED0-A3D1-48A2-A26B-7596BF6614BB}
AppName=Get Eat Fish
AppVersion=0.5
;AppVerName=Get Eat Fish 0.5
AppPublisher=GolgleEarth
AppPublisherURL=http://www.kpu.ac.kr
AppSupportURL=http://www.kpu.ac.kr
AppUpdatesURL=http://www.kpu.ac.kr
DefaultDirName={pf}\Get Eat Fish
DisableProgramGroupPage=yes
OutputDir=C:\Users\Chikawoshi\Desktop
OutputBaseFilename=get_eat_fish_setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Chikawoshi\Documents\GitHub\2DGP\dist\mygame.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Chikawoshi\Documents\GitHub\2DGP\dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\Get Eat Fish"; Filename: "{app}\mygame.exe"
Name: "{commondesktop}\Get Eat Fish"; Filename: "{app}\mygame.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\mygame.exe"; Description: "{cm:LaunchProgram,Get Eat Fish}"; Flags: nowait postinstall skipifsilent

